### ISSUE TITLE
Add information to Labels Overview Report

### ISSUE THREAD

**Issue by mrry550** [openshift/sprint_tools#22]
Jeremy Eder requested the following information to be added to the labels overview report (would also be good for the blocked category, but not sure docs & security need this information). 

Members
Due Date
Which Column the card is in
Latest Comment (if any-- not entirely sure if we can do this and have it make sense).

**Comment by danmcp** [comment]
@mrry550 The list column is already there.  I have concerns about the rest:

Members can be really long.
Most cards don't have due dates
Comment would be hard to show and the api doesn't exist.
