### ISSUE TITLE
How to define Trello URI

### ISSUE THREAD

**Issue by cmoulliard** [openshift/sprint_tools#65]
Is it possible to document how we can configure the Trello URI in order to avoid this error 

```
./trello list
Error with org: bad URI(is not URI?): https://api.trello.com/1/organizations/<organication short name>
```

**Comment by dobbymoodge** [comment]
You have to configure the `organization_id` and `organization_name` in `trello.yml` here: https://github.com/openshift/sprint_tools/blob/master/config/trello.yml#L30

**Comment by cmoulliard** [comment]
And where should I define the Trello App Key which is used to get the token for an organisation ? I'm confused as the Trello.yml file contains 4 variables to configure the Customer keys and Oauth ...

**Comment by dobbymoodge** [comment]
You need to follow lines 1-3: https://github.com/openshift/sprint_tools/blob/master/config/trello.yml#L1
Get the app key from the first URL, hit the second URL with the App Key (and replace "Openshift" with your app user), and then do the same for the third URL. IIRC that will get you the appropriate keys/tokens/secrets to populate the settings on lines 5-8.

**Comment by dobbymoodge** [comment]
Actually, I think I was wrong - you probably want to hit the URLs in just lines 1 and 3. The "name" field doesn't need to match any user, it's just the name listed for that set of credentials in your user's "account" config view in trello. It can be anything you want.

**Comment by dobbymoodge** [comment]
Also, the `consumer_secret` string is at the bottom of the page from the URL on line 1.

**Comment by dobbymoodge** [comment]
Hmmm, looks like you'll also need to hit `https://trello.com/1/authorize?key=<appKey>&name=OpenShift&expiration=never` - make sure the `name` field matches what you used for the `https://trello.com/1/connect?...` URL.

**Comment by dobbymoodge** [comment]
Clear as mud! :D

**Comment by dobbymoodge** [comment]
@cmoulliard can we close this out now?

**Comment by cmoulliard** [comment]
I don't have the time to work on that for the moment. So we can close it. If someone can improve the doc, that should be fantastic
