### ISSUE TITLE
Add issue tracking board functionality

### ISSUE THREAD

**Issue by dobbymoodge** [openshift/sprint_tools#93]
We need a way to set up a board to track problems and issues for specific problem domains. There should be one or more "Tracking Lists", which work similarly to Epic lists and card groups, but which are specified in the yaml config instead of hardcoded. There should also be one or more "Issue Lists" which function like the active sprint lists w.r.t. card groups, also specified in the yaml config and belonging to a specific Tracking List.

The configuration for these boards should be separate from the Teams section - i.e. like Dependent Work Boards - so that we can opt to exclude them from the regular sprint board processing done by `trello update` etc.

**Comment by jupierce** [comment]
```
tracking:
  Clusters:
    - Issues
    - Upgrades
    - Configuration Requests
    - Doing
    - Done
```

**Comment by jupierce** [comment]
Hold on implementation until I can explore butler for trello a bit.

**Comment by jupierce** [comment]
Butler seems to handle my use cases pretty well. Probably the easiest solution for me, so closing this unless you think it will be needed for others.
